  CREATE TABLE "DOCUMENTO" 
   (	"ID_DOCUMENTO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_SOLICITUD" NUMBER(*,0) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(100), 
	"NOMBRE_ARCHIVO" VARCHAR2(200), 
	"RUTA_ARCHIVO" VARCHAR2(500), 
	"FECHA_GENERACION" DATE DEFAULT SYSDATE, 
	"ESTADO" VARCHAR2(50), 
	"GENERADO_POR" VARCHAR2(100), 
	 CONSTRAINT "PK_DOCUMENTO" PRIMARY KEY ("ID_DOCUMENTO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "HISTORIAL_ESTADO_SOLICITUD" 
   (	"ID_HISTORIAL" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_SOLICITUD" NUMBER(*,0) NOT NULL ENABLE, 
	"ESTADO_ANTERIOR" VARCHAR2(50), 
	"ESTADO_NUEVO" VARCHAR2(50), 
	"FECHA_CAMBIO" DATE DEFAULT SYSDATE, 
	"USUARIO_RESPONSABLE" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_HISTORIAL" PRIMARY KEY ("ID_HISTORIAL")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "NOTIFICACION" 
   (	"ID_NOTIFICACION" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER(*,0) NOT NULL ENABLE, 
	"MENSAJE" VARCHAR2(500), 
	"FECHA_ENVIO" DATE DEFAULT SYSDATE, 
	"TIPO" VARCHAR2(50), 
	"IMPORTANCIA" VARCHAR2(50), 
	"ENLACE" VARCHAR2(300), 
	"ESTADO" VARCHAR2(50), 
	 CONSTRAINT "PK_NOTIFICACION" PRIMARY KEY ("ID_NOTIFICACION")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PROGRAMA_ACADEMICO" 
   (	"ID_PROGRAMA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(200) NOT NULL ENABLE, 
	"ESCUELA" VARCHAR2(200) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PROGRAMA_ACADEMICO" PRIMARY KEY ("ID_PROGRAMA")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "REQUISITO" 
   (	"ID_REQUISITO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TIPO" VARCHAR2(100), 
	"OBLIGATORIO" CHAR(1), 
	"ID_PROGRAMA" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(300), 
	 CHECK (OBLIGATORIO IN ('S','N')) ENABLE, 
	 CONSTRAINT "PK_REQUISITO" PRIMARY KEY ("ID_REQUISITO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "REQUISITO_CUMPLIDO" 
   (	"ID_SOLICITUD" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_REQUISITO" NUMBER(*,0) NOT NULL ENABLE, 
	"CUMPLIDO" CHAR(1), 
	"FECHA_VALIDACION" DATE, 
	"VALIDADOR" NUMBER(*,0), 
	"OBSERVACIONES" VARCHAR2(300), 
	"EVIDENCIA_URL" VARCHAR2(500), 
	 CHECK (CUMPLIDO IN ('S','N')) ENABLE, 
	 CONSTRAINT "PK_REQ_CUMPLIDO" PRIMARY KEY ("ID_SOLICITUD", "ID_REQUISITO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SOLICITUD_GRADO" 
   (	"ID_SOLICITUD" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER(*,0) NOT NULL ENABLE, 
	"FECHA_SOLICITUD" DATE DEFAULT SYSDATE, 
	"ESTADO" VARCHAR2(50) DEFAULT 'PENDIENTE', 
	"OBSERVACIONES" VARCHAR2(500), 
	"FECHA_REVISION" DATE, 
	"FECHA_APROBACION" DATE, 
	"PERIODO_ACADEMICO" VARCHAR2(50), 
	 CONSTRAINT "PK_SOLICITUD_GRADO" PRIMARY KEY ("ID_SOLICITUD")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USUARIO" 
   (	"ID_USUARIO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE_COMPLETO" VARCHAR2(200) NOT NULL ENABLE, 
	"CORREO_INSTITUCIONAL" VARCHAR2(150) NOT NULL ENABLE, 
	"ROL" VARCHAR2(50), 
	"CONTRASENA" VARCHAR2(200) NOT NULL ENABLE, 
	"TELEFONO" VARCHAR2(20), 
	"ACTIVO" CHAR(1) DEFAULT 'S', 
	"ID_PROGRAMA" NUMBER(*,0), 
	 CHECK (ROL IN ('ESTUDIANTE','ADMIN','DOCENTE')) ENABLE, 
	 CHECK (ACTIVO IN ('S','N')) ENABLE, 
	 CONSTRAINT "PK_USUARIO" PRIMARY KEY ("ID_USUARIO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_USUARIO_CORREO" UNIQUE ("CORREO_INSTITUCIONAL")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "IDX_DOC_SOLICITUD" ON "DOCUMENTO" ("ID_SOLICITUD") 
  ;

  CREATE INDEX "IDX_HIST_SOLICITUD" ON "HISTORIAL_ESTADO_SOLICITUD" ("ID_SOLICITUD") 
  ;

  CREATE INDEX "IDX_HIST_USUARIO" ON "HISTORIAL_ESTADO_SOLICITUD" ("USUARIO_RESPONSABLE") 
  ;

  CREATE INDEX "IDX_NOTIF_USUARIO" ON "NOTIFICACION" ("ID_USUARIO") 
  ;

  CREATE INDEX "IDX_RC_REQUISITO" ON "REQUISITO_CUMPLIDO" ("ID_REQUISITO") 
  ;

  CREATE INDEX "IDX_RC_SOLICITUD" ON "REQUISITO_CUMPLIDO" ("ID_SOLICITUD") 
  ;

  CREATE INDEX "IDX_RC_VALIDADOR" ON "REQUISITO_CUMPLIDO" ("VALIDADOR") 
  ;

  CREATE INDEX "IDX_REQ_PROGRAMA" ON "REQUISITO" ("ID_PROGRAMA") 
  ;

  CREATE INDEX "IDX_SOLICITUD_USUARIO" ON "SOLICITUD_GRADO" ("ID_USUARIO") 
  ;

  CREATE INDEX "IDX_USUARIO_PROGRAMA" ON "USUARIO" ("ID_PROGRAMA") 
  ;

  CREATE UNIQUE INDEX "PK_DOCUMENTO" ON "DOCUMENTO" ("ID_DOCUMENTO") 
  ;

  CREATE UNIQUE INDEX "PK_HISTORIAL" ON "HISTORIAL_ESTADO_SOLICITUD" ("ID_HISTORIAL") 
  ;

  CREATE UNIQUE INDEX "PK_NOTIFICACION" ON "NOTIFICACION" ("ID_NOTIFICACION") 
  ;

  CREATE UNIQUE INDEX "PK_PROGRAMA_ACADEMICO" ON "PROGRAMA_ACADEMICO" ("ID_PROGRAMA") 
  ;

  CREATE UNIQUE INDEX "PK_REQUISITO" ON "REQUISITO" ("ID_REQUISITO") 
  ;

  CREATE UNIQUE INDEX "PK_REQ_CUMPLIDO" ON "REQUISITO_CUMPLIDO" ("ID_SOLICITUD", "ID_REQUISITO") 
  ;

  CREATE UNIQUE INDEX "PK_SOLICITUD_GRADO" ON "SOLICITUD_GRADO" ("ID_SOLICITUD") 
  ;

  CREATE UNIQUE INDEX "PK_USUARIO" ON "USUARIO" ("ID_USUARIO") 
  ;

  CREATE UNIQUE INDEX "UQ_USUARIO_CORREO" ON "USUARIO" ("CORREO_INSTITUCIONAL") 
  ;
