  CREATE TABLE "DOCUMENTO" 
   (	"ID_DOCUMENTO" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_SOLICITUD" VARCHAR2(50) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(100) NOT NULL ENABLE, 
	"RUTA_ARCHIVO" VARCHAR2(100) NOT NULL ENABLE, 
	"FECHA_DE_GENERACION" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	 CONSTRAINT "DOCUMENTO_PK" PRIMARY KEY ("ID_DOCUMENTO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "NOTIFICACION" 
   (	"ID_NOTIFICACION" VARCHAR2(50) NOT NULL ENABLE, 
	"ID_USUARIO" VARCHAR2(20) NOT NULL ENABLE, 
	"MENSAJE" VARCHAR2(200) NOT NULL ENABLE, 
	"FECHA_DE_ENVIO" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "NOTIFICACION_PK" PRIMARY KEY ("ID_NOTIFICACION")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "REQUISITOS" 
   (	"ID_REQUISITO" VARCHAR2(50) NOT NULL ENABLE, 
	"TIPO" CHAR(25) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(150) NOT NULL ENABLE, 
	 CONSTRAINT "REQUISITOS_PK" PRIMARY KEY ("ID_REQUISITO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "REQUISITO_CUMPLIDO" 
   (	"VALIDADOR" VARCHAR2(50) NOT NULL ENABLE, 
	"ID_SOLICITUD" VARCHAR2(50) NOT NULL ENABLE, 
	"ID_REQUISITO" VARCHAR2(50) NOT NULL ENABLE, 
	"CUMPLIDO" VARCHAR2(150) NOT NULL ENABLE, 
	"FECHA_VALIDACION" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE, 
	 CONSTRAINT "REQUISITO_CUMPLIDO_PK" PRIMARY KEY ("VALIDADOR")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SOLICITUD_GRADO" 
   (	"ID_SOLICITUD" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"ID_USUARIO" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"FECHA_SOLICITUD" DATE NOT NULL ENABLE, 
	"ESTADO" CHAR(25 CHAR) NOT NULL ENABLE, 
	"OBSERVACIONES" VARCHAR2(150 CHAR), 
	 CONSTRAINT "SOLICITUD_GRADO_PK" PRIMARY KEY ("ID_SOLICITUD")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USUARIO" 
   (	"ID_USUARIO" VARCHAR2(20) NOT NULL ENABLE, 
	"NOMBRE_COMPLETO" VARCHAR2(50) NOT NULL ENABLE, 
	"CORRE_INSTITUCIONAL" VARCHAR2(50) NOT NULL ENABLE, 
	"ROL" CHAR(20) NOT NULL ENABLE, 
	"CONTRASEÑA" VARCHAR2(150) NOT NULL ENABLE, 
	 CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "DOCUMENTO" ADD CONSTRAINT "DOCUMENTO_FK" FOREIGN KEY ("ID_SOLICITUD")
	  REFERENCES "SOLICITUD_GRADO" ("ID_SOLICITUD") ENABLE;

   COMMENT ON COLUMN "DOCUMENTO"."ID_DOCUMENTO" IS 'Numero de documento del usuario';
   COMMENT ON COLUMN "DOCUMENTO"."ID_SOLICITUD" IS 'Numero de solicitud del usuario';
   COMMENT ON COLUMN "DOCUMENTO"."TIPO" IS 'Tipo de documento solicitado';
   COMMENT ON COLUMN "DOCUMENTO"."RUTA_ARCHIVO" IS 'Ruta del documento solicitado';
   COMMENT ON COLUMN "DOCUMENTO"."FECHA_DE_GENERACION" IS 'Fecha de generación del documento';

  ALTER TABLE "NOTIFICACION" ADD CONSTRAINT "NOTIFICACION_CON" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "USUARIO" ("ID_USUARIO") ENABLE;

  ALTER TABLE "REQUISITO_CUMPLIDO" ADD CONSTRAINT "REQUISITO_CUMPLIDO_CON" FOREIGN KEY ("ID_SOLICITUD")
	  REFERENCES "SOLICITUD_GRADO" ("ID_SOLICITUD") ENABLE;
  ALTER TABLE "REQUISITO_CUMPLIDO" ADD CONSTRAINT "REQUISITO_CUMPLIDO_FK" FOREIGN KEY ("ID_REQUISITO")
	  REFERENCES "REQUISITOS" ("ID_REQUISITO") ENABLE;

  ALTER TABLE "SOLICITUD_GRADO" ADD CONSTRAINT "SOLICITUD_GRADO_CON" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "USUARIO" ("ID_USUARIO") ENABLE;

  CREATE UNIQUE INDEX "DOCUMENTO_PK" ON "DOCUMENTO" ("ID_DOCUMENTO") 
  ;

  CREATE UNIQUE INDEX "NOTIFICACION_PK" ON "NOTIFICACION" ("ID_NOTIFICACION") 
  ;

  CREATE UNIQUE INDEX "REQUISITOS_PK" ON "REQUISITOS" ("ID_REQUISITO") 
  ;

  CREATE UNIQUE INDEX "REQUISITO_CUMPLIDO_PK" ON "REQUISITO_CUMPLIDO" ("VALIDADOR") 
  ;

  CREATE UNIQUE INDEX "SOLICITUD_GRADO_PK" ON "SOLICITUD_GRADO" ("ID_SOLICITUD") 
  ;

  CREATE UNIQUE INDEX "USUARIO_PK" ON "USUARIO" ("ID_USUARIO") 
  ;